# This is a basic workflow to help you get started with Actions

on:
  push:
    branches:
    - master

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Outdated gems
    steps:
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.0
      - uses: Bhacaz/bundler-outdated-action@v0.2
        with:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          REPOSITORY: ${{env.GITHUB_REPOSITORY}}
      - run: 'ruby src/main.rb' 
