# This is a basic workflow to help you get started with Actions

on:
  push:
    branches:
    - master

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Outdated gems
    steps:
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: 'Pull outdated gem script'
        uses: actions/checkout@v2
        with:
          repository: 'Bhacaz/bundler-outdated-action'
      - name: 'Check outdated gems'
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          GEMFILE_REPOSITORY: ${{env.GITHUB_REPOSITORY}} 
        run: 'ruby src/main.rb'
